### ISSUE TITLE
The build-image script causes issues with linking Docker containers together

### ISSUE THREAD

**Issue by thomashoneyman** [jml/servant-template#21] opened 2017-07-31 00:17 UTC
Hi Jonathan!

Thank you for making this template. I've adapted parts of your project into mine and it's been tremendously helpful.

One thing I've unsuccessfully tried to adapt is the build-image script you put together. I'd love to use it, because the resulting image in my test project is just 33mb vs. the 2gb+ that results from my custom Dockerfile. 

### The Issue

The build-image script seems to cause an issue with linking containers together that doesn't happen if you aren't using the script. 

If I build the image for a [tiny test repo I made](https://github.com/saylu/haskell-deploy), using my custom Dockerfile, I'm successfully able to start all services and run the application. However, if I use the build script, while both services start just fine, I get an error linking the containers and the application will not allow any database connections.

### Reproducing the Issue

To test what's going on, I made this minimal example repository:
https://github.com/saylu/haskell-deploy

You can reproduce this behavior by cloning the repository and running `make image` and `docker-compose up` for the build-image script, or `docker build -t saylu/haskell-deploy .` and `docker-compose up` for the custom Dockerfile. In either case, both services should start successfully. 

The difference comes when you visit `localhost` in the browser. Using the build-image script, I see this error:

```
libpq: failed (could not translate host name "db" to address: Name or service not known)
```

This is in reference to the "db" service in my `docker-compose.yml` file. There's some error with linking the containers together.

However, if you instead build with my Dockerfile, this works. If you haven't set up the database, you'll see a SQL error, which is to be expected because the database doesn't exist, but more importantly it means the containers are properly linked together.

**Docker Versions**
Docker version 17.06.0-ce, build 02c1d87
docker-compose version 1.14.0, build c7bdf9e

### Next Steps

I would love to resolve this problem on my own and submit a pull request, but I haven't been able to figure out exactly what's going on in the way this image is being created that could cause these linking issues. I've been in conversation with others in the #fpchat Slack channel who have the same linking problem when relying on this script and have had to resort to massive (500mb, 1gb, or more) images instead.

I'd love to hear how I can help with this issue or if you have any ideas of the cause.

**Comment by tippenein** [comment] 2017-07-31 00:59
From what I can tell by poking at the /tmp directory created by build-image, the libpq shows up as an ordinary file even though it is a symlink in the fs.

```
ls -l /tmp/tmp.Yq6FF6Ye9d/usr/lib/x86_64-linux-gnu/libpq.so.5                             
-rw-r--r-- 1 tippenein tippenein 194544 Oct 27  2016 usr/lib/x86_64-linux-gnu/libpq.so.5
------------------------------------------------------------
 ls /usr/lib/x86_64-linux-gnu/libpq.                                   
libpq.a       libpq.so@     libpq.so.5@   libpq.so.5.9

```diff /usr/lib/x86_64-linux-gnu/libpq.so.5.9  /tmp/tmp.Yq6FF6Ye9d/usr/lib/x86_64-linux-gnu/libpq.so.5
Binary files /usr/lib/x86_64-linux-gnu/libpq.so.5.9 and  /tmp/tmp.Yq6FF6Ye9d/usr/lib/x86_64-linux-gnu/libpq.so.5 differ
```
So it must be the same issue as reported here : https://github.com/moby/moby/issues/30213

`docker cp -L` isn't completely resolving the symlinks ?

**Comment by jml** [comment] 2017-08-03 12:47
FWIW, I'd like to look into better ways to generate a static executable. 

I *think* at least part of the issue is that GHC needs static versions of any C libraries to be installed on the system, and that these are not installed by default.

Probably the next thing I'll do personally is look into building my Haskell executables and images using [Bazel](https://bazel.build/), as that has the nice functional properties of Nix, a clean Python-like build language, and has some (growing!) support for cross-compilation, which is important to me as a Mac user.

**Comment by thomashoneyman** [comment] 2017-08-03 20:42
I'm not sure exactly what Stack is doing under the hood, but using their Docker integration with an Ubuntu image works just fine and produces a 222mb image (an example is in the same repository I shared earlier). 

It also works with an Alpine image so long as you don't have many C dependencies (for the same reason you cited), creating roughly a ~33mb image. Sticking with the former (Ubuntu) might be a simple way to have things work in this repository when you add a DB like Postgres. But perhaps that's out of scope.

Unfortunately, I didn't see a way to actually see what they're doing, but it seems to be a similar approach to your script.

If there's no straightforward answer for your build script, no worries -- just thought I'd raise the issue as I've heard of your repository several times as a good example project and ran into trouble there. You can feel free to close the issue in that case.

Cheers,
T

**Comment by jml** [comment] 2017-08-04 10:37
Thanks.

I'll close for now, but if some enterprising individual wants to re-open to tackle it, they should feel most free to do so.

**Closed as completed by jml** 2017-08-04 10:37 UTC
